package com.valhalla.valhalla

import android.content.Context
import java.io.File

/**
 * Writes a valhalla.json config pointing at a tile_extract `.tar` and returns its absolute path.
 *
 * The valhalla-mobile 0.5.1 `.so` routes ONLY from a memory-mapped `.tar` (`tile_extract`), NOT
 * from a loose `tile_dir` (that throws a native `basic_string` crash on this build). We download
 * ONE pre-assembled all-India valhalla_tiles.tar straight to disk and point here at that tar.
 *
 * The config is a template asset generated by the same Valhalla version that built the tiles
 * (gis-ops/valhalla image); we only substitute the tile_extract path at runtime.
 */
object ValhallaConfig {

    private const val TEMPLATE_ASSET = "valhalla_config_template.json"
    private const val PLACEHOLDER = "__TILE_EXTRACT__"

    fun write(context: Context, tileExtractPath: String): String {
        val template = context.assets.open(TEMPLATE_ASSET).bufferedReader().use { it.readText() }
        // JSON-escape the path (backslashes/quotes are not expected on Android but be safe).
        val safePath = tileExtractPath.replace("\\", "\\\\").replace("\"", "\\\"")
        val config = template.replace(PLACEHOLDER, safePath)

        val file = File(context.filesDir, "valhalla.json")
        file.writeText(config)
        return file.absolutePath
    }
}
