package com.valhalla.valhalla

import android.content.Context
import java.io.File

/**
 * Writes a valhalla.json config pointing at a tile DIRECTORY (loose .gph tiles) and returns
 * its absolute path.
 *
 * We use `tile_dir` (not a single `tile_extract` .tar) so multiple downloaded routing packs can
 * be extracted into ONE shared directory and STACK — the app downloads a base pack + per-state
 * packs, extracts them all into the same dir, and Valhalla routes across them (including across
 * state borders). Verified on-device engine: base+Telangana+Karnataka stacked routes
 * Hyderabad->Bangalore (569 km), and routing into an un-installed state fails gracefully.
 *
 * The config is a template asset generated by the same Valhalla version that built the tiles
 * (gis-ops/valhalla image), guaranteeing every required node is present. We only substitute the
 * tile_dir path at runtime.
 */
object ValhallaConfig {

    private const val TEMPLATE_ASSET = "valhalla_config_template.json"
    private const val PLACEHOLDER = "__TILE_DIR__"

    fun write(context: Context, tileDirPath: String): String {
        val template = context.assets.open(TEMPLATE_ASSET).bufferedReader().use { it.readText() }
        // JSON-escape the path (backslashes/quotes are not expected on Android but be safe).
        val safePath = tileDirPath.replace("\\", "\\\\").replace("\"", "\\\"")
        val config = template.replace(PLACEHOLDER, safePath)

        val file = File(context.filesDir, "valhalla.json")
        file.writeText(config)
        return file.absolutePath
    }
}
